### ISSUE TITLE
Lacking customization

### ISSUE THREAD

**Issue by hope-portal-services** [bay0/react-app-protect#1]
Styled component classes override, making it impossible to customize passed the wrapper class without targeting specific elements like `input` or `button` - Would be better if you included a styles prop on the main `Protect` wrapper to pass in custom styles for the inner components, ie: button, input, box, header.

Example:

```
<Protect styles={{
     input: { width: "100%" },
     button: { background: "blue" },
     header: { background: "red" },
     wrapper: { background: "green" }
}}>{children}</Protect>
```

**Comment by bay0** [comment]
Will add that in the next release :)

**Comment by bay0** [comment]
Updated to version 1.0.7

https://www.npmjs.com/package/react-app-protect/v/1.0.7
