### ISSUE TITLE
Getting a warning displayed in console 'Received `false` for a non-boolean attribute `className`.'

### ISSUE THREAD

**Issue by danrostron** [bay0/react-app-protect#5]
Using as per example in readme results in the following warning in console:

![image](https://user-images.githubusercontent.com/2691545/132284906-d2645c2a-77c3-44ef-94ed-d4f728a58f18.png)

**Comment by bay0** [comment]
Don't pass a boolean to className, it expects a string.
If you don't want to use the prop className don't use it.
